---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::885171081998:role/eksctl-ekslab-addon-iamserviceaccount-defaul-Role1-1QZEDEWI08RUG
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: flink-service-account
  namespace: default
secrets:
- name: flink-service-account-token-9sjhg
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-role-binding-flink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: flink-service-account
  namespace: default